import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.product.createMany({
    data: [
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
      {
        name: "Classic Ceiling Fan",
        price: 3500,
        stock: 15,
        category: "Ceiling Fan",
        rating: 4.5,
        description: "A stylish and energy-efficient ceiling fan.",
        image: "/uploads/ceiling-fan.jpg",
        sku: "classic_ceiling_fan_1",
      },
      {
        name: "Modern Pedestal Fan",
        price: 2800,
        stock: 25,
        category: "Pedestal Fan",
        rating: 4.2,
        description: "Powerful air delivery with sleek design.",
        image: "/uploads/pedestal-fan.jpg",
        sku: "modern_pedestal_fan_2",
      },
      {
        name: "Wall Fan Deluxe",
        price: 3200,
        stock: 18,
        category: "Wall Fan",
        rating: 4.7,
        description: "Compact wall-mounted fan with remote control.",
        image: "/uploads/wall-fan.jpg",
        sku: "wall_fan_deluxe_3",
      },
    ],
  });

  console.log("✅ Seed data inserted successfully!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error("❌ Error seeding data:", e);
    await prisma.$disconnect();
    process.exit(1);
  });
